steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "gcr.io/go-expert-weather-api/api", ".", "-f", "Dockerfile" ]

  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/go-expert-weather-api/api" ]